### ISSUE TITLE
Lot's of HTTP api spamming after installing the extension

### ISSUE THREAD

**Issue by BrianStark** [NON906/chara-searcher#2]
After installing this extension, I get the spam you see below with every click I make on my console.
Is this something that can be fixed, it is quite annoying.
Thanks in advance.

![image](https://github.com/user-attachments/assets/c0f890b0-fbaf-4cdc-83f0-31ab06b4a9c4)

**Comment by NON906** [comment]
I'm sorry.
Fixed with 381551ce688df8da2699ae0c36f4be75629a011c.

**Comment by BrianStark** [comment]
Thankksssss, other than that i would love to share that the extension is a huge help, keep up the good work 😊👍🏻
