### ISSUE TITLE
Blowing up a noobers c-drive

### ISSUE THREAD

**Issue by eLBe-SD** [NON906/chara-searcher#4]
Hey
Sorry at First, absolutely code-noob & copy-paster Here. I love playing around with Stable Diffusion and your Addon doing a really great job to create own LoRas.
But after running some different picture sets through it, it seems to save the old sets (which i don't need anymore) somewhere and blowing up my c-drive, while everything is installed on my d-drive.
With every new Set, the Addon pregiving me Untitled_1, Untitled_2, Untitled_3, etc. and showing me previews of pictures from old sets in the WebUI from which i need to get rid off before i can export.
Thought about some temporary files, but can't find anything.
Can you tell me what i am doing wrong or where to find these old data to delete it?
Kind regards

**Comment by NON906** [comment]
When I checked, it seems that they are saved in the following directory.

C:\Users\username\AppData\Local\Temp\gradio

**Comment by eLBe-SD** [comment]
Thank you! Seems that I was blind...
